### PR TITLE
feat(patches/alpha-background): add experimental alpha-background patch

### LINKED ISSUE #111: Add patch for alpha-background support
Here's a patch from https://github.com/jonrubens/emacs that adds support for `alpha-background` on MacOS (set alpha of background while leaving text opaque; it's great for doc popup frames). It would be great if you could add this as an option to your script -- I see you've got a few such options which download patches and apply them.

This patch applies OK to emacs master (a268496727, Aug 20 2024).
[ns-alpha-background-v2.patch](https://github.com/user-attachments/files/16682084/ns-alpha-background-v2.patch)

### PR DESCRIPTION
**Pull request by jimeh**
Resolves #111

### CODE REVIEW

**Comment by jimeh** [comment]
@jonrubens I hope you don't mind if I borrow the changes in your `ns-alpha-background` branch as a optional patch for use in my build script. If you have any objections, I'm happy to drop it.

The patch feature includes a static `*.patch` file for Emacs 29.x, and dynamically downloads a patch for Emacs 30.x and 31.x from GitHub.

If you don't mind others making use of your alpha-background changes, I think it'd be nice to get a patch submitted to [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus/tree/master) as well. They already maintain a number of very nice patches.

**Comment by jonrubens** [comment]
You can absolutely include my change as a patch.

FYI, I have submitted the code to the Emacs master branch, so hopefully it will get pulled in for Emacs 31.

**Comment by jimeh** [comment]
@jonrubens Not sure if you've noticed, but when stepping through alpha-background with +1 or -1, I notice some odd flickering and color changes with [my config](https://github.com/jimeh/.emacs.d). Essentially, every second or third value yields a slightly more yellowish background color than others, making it look like a slight flicker when quickly stepping up/down the alpha-background one value at a time.

I'm not sure if it's simply how the math works out when applying transparency to the colors of my theme, or if it's some odd bug with `alpha-background`. A similar thing seems to happen when setting `alpha` as well, but it's harder to tell cause the intensity curve is much stronger in the 90-100 range than it is for `alpha-background`.

If you're curious to dig deeper, I've got screenshots ranging with values 70 to 100 for both `alpha-background` and `alpha`, with Emacs placed in front of a solid white background:

- https://share.jimeh.me/emacs-alpha-background-levels-YM5icz490jr0.zip
- https://share.jimeh.me/emacs-alpha-levels-0DxdWdZLH5aR.zip

I used [my transparency helpers](https://github.com/jimeh/.emacs.d/blob/021fba9c73987d8a84d3d8a031c367de0e075938/modules/ui/siren-transparency.el) for quickly changing the value, and here's a variant that uses `alpha-background` instead of `alpha`:

<details>
  <summary><code>siren-transparency.el</code>:</summary>

```elisp
;;; siren-transparency.el --- jimeh's Emacs Siren: Emacs Frame transparency.

;;; Commentary:

;; Basic helpers and configuration for frame transparency.

;;; Code:

(require 'siren-ui)

(defgroup siren-transparency nil
  "Options for the Siren transparency."
  :group 'siren-ui)

(defcustom siren-transparency-default-level 90
  "The default frame transparency level for Emacs frames."
  :type 'number
  :set (lambda (symbol value)
         (set-default symbol value)
         (setf (alist-get 'alpha-background default-frame-alist) value))
  :group 'siren)

(defun siren-transparency-decrease ()
  "Decrease level of transparency for the current frame."
  (interactive)
  (let ((current (or (frame-parameter nil 'alpha-background) 100)))
    (if (> current 0)
        (let ((new-level (+ current -1)))
          (siren-transparency new-level)
          (message "Frame transparency set to %s" new-level))
      (message "This is a minimum value of transparency!"))))

(defun siren-transparency-increase ()
  "Increase level of transparency for the current frame."
  (interactive)
  (let ((current (or (frame-parameter nil 'alpha-background) 100)))
    (if (< current 100)
        (let ((new-level (+ current +1)))
          (siren-transparency new-level)
          (message "Frame transparency set to %s" new-level))
      (message "This is a minimum value of transparency!"))))

(defun siren-transparency (num)
  "Set level of transparency for the current frame by providing NUM."
  (interactive "nEnter transparency level in range 0-100: ")
  (set-frame-parameter nil 'alpha-background (cond ((> num 100) 100)
                                                   ((< num 0) 0)
                                                   (t num))))

;; Keybindings
(siren-general-define-key
 "C-M-|" 'siren-transparency
 "C-M-<" 'siren-transparency-decrease
 "C-M->" 'siren-transparency-increase)

(provide 'siren-transparency)
;;; siren-transparency.el ends here
```

</details>

**Comment by jonrubens** [comment]
I haven't ever noticed the color flicker. It's been a while since I wrote the code but my first pass guess is that it is something in how MacOS does transparency and not on the emacs side of things. I might dig into that further but I don't think there is anything in what I wrote that breaks down the color values to RGB besides simply applying the alpha component. It could be a consequence of how MacOS rounds when taking a 0-100 multiplier and converts to 0-255.

As for the intensity curve, that is something that bothered me and it never felt right. I wanted the transparency at 90% alpha to match 90% alpha-background but I couldn't figure out why it doesn't. I had an idea to fix it by translating the alpha-background curve to match, but it felt to hacky when there must be some layer being drawn that should be able to be fixed.

**Comment by bramadams** [comment]
@jimeh Thanks for integrating @jonrubens' support for alpha-background in your build!

However, using `(set-frame-parameter nil 'alpha-background 50)` does not seem to have any impact on my latest 30.0.92 build. Is there a way to check if the patch was incorporated? I used `./build-emacs-for-macos --alpha-background --no-archive emacs-30.0.92` as build command.

**Comment by jimeh** [comment]
Oh, weird. I'm not aware of any way in a running Emacs instance aside from setting the frame parameter. However you can check the C sources for presence of the patch's changes either within the Emacs.app bundle under `Contents/Resources/src`, or in the full source tree used to build emacs under the `sources` directory.

**Comment by bramadams** [comment]
@jimeh Thanks for the quick reply. Turns out the patch was not applied. After removing the source directory and rerunning the build, it's working now. The alpha-background setting looks amazing!

**Comment by jimeh** [comment]
Ah, right. Yeah the buildscript tries to re-use existing outputs (tarballs, source directories, etc.) if they exist. I should really add a `--scratch` or `--clean` flag or something where it ignores that stuff and just throws away anything it finds and builds from scratch.

Mostly that stuff is just useful for me I think while I'm working on the build script... lol

**Pull request merged**
