### PR TITLE
added support for building on Big Sur

### PR DESCRIPTION
**Pull request by claford-v-lawrence**
Curtsy of https://apple.stackexchange.com/questions/408999/gfortran-compiler-error-on-mac-os-big-sur

### CODE REVIEW

**Comment by AllenDang** [comment]
@claford-v-lawrence Thanks for your effort! I managed to build on Big Sur, but launch Emacs.app reports a error 'library not found for -lSystem', does this happen in your build?

**Comment by jimeh** [comment]
@claford-v-lawrence thanks for this, I'm finally planning to upgrade my own machine to Big Sur this weekend. Can you confirm that native compilation works with builds produced with this PR? The reason I'm asking is cause I would imagine the same path needs to be added to `LIBRARY_PATH` at runtime too via the `patches/native-comp-env-setup.patch` patch.

@AllenDang there's some dicussion over on https://github.com/d12frosted/homebrew-emacs-plus/issues/187 suggesting a reinstall of gcc/libgccjit might help:

```
brew reinstall gcc libgccjit
```

If that doesn't work, it's probably related to the runtime stuff I've mentioned above, try adding this at the very beginning of your `early-init.el` or `init.el` file:

```elisp
(setenv "LIBRARY_PATH" (concat (getenv "LIBRARY_PATH") ":" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"))
```

If that works, I'll update the patch accordingly too so you won't need to modify your config.

**Comment by AllenDang** [comment]
@jimeh Yes, I can confirm that native compilation works with this PR. And add that line to early-init.el does solve the problem.

**Comment by claford-v-lawrence** [comment]
@jimeh Hmmm, this actually doesn't quite work right for me just now, it compiles alright, but when I run it in guy, it now reports
`Emacs.app/Contents/Macos/lib/gcc` not found, even with the library path.
I'm using hash `be907b0ba82c2a65e0468d50653cae8a7cf5f16b`.

@AllenDang Does it work alright for you? I'm curious to hear about your setup:P

**Comment by jimeh** [comment]
I've incorporated the changes from this PR into #26, so I can also add changes to the native-comp-env-setup patch to add the Xcode CLI path to `LIBRARY_PATH` at runtime too.

Hence I'm closing this PR, as we can continue the discussion over on #26 :)

**Pull request closed without merging**
